### PR TITLE
Hotfix: reverted a change which causes a crash

### PR DESCRIPTION
**Pull request by JackRainy**
Hotfix to avoid a crash on any start of the game caused by PR #6468 until better solution is found

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
@alexban011  @Azzurite  @GGGuenni  @itanasi  @letstalkaboutdune  @Pitel  @SimonCeder  @will-ca  @xlenstra  
(from recent PR list, alphabetically)

I **_hope_** this is not necessary, and a Build->Clean followed by File -> Invalidate Cache _will_ clear up the madness that kotlin no longer knows its own standard library. Please do comment on success _or_ failure.

**Comment by alexban011** [comment]
OS: Windows 10
	Windows 10 Pro Version 21H2 (Build 19044)
Java: Oracle Corporation 11.0.11+9-b60-7590822
	Max Memory: 4062 MB


--------------------------------


**Message:**
```
java.lang.NoSuchMethodError: 'int kotlin.CharCodeKt.access$getCode$p(char)'
	at com.unciv.ui.utils.KeyCharAndCode$Companion.makeChar(KeyPressDispatcher.kt:71)
	at com.unciv.ui.utils.KeyCharAndCode$Companion.ctrl(KeyPressDispatcher.kt:76)
	at com.unciv.ui.worldscreen.WorldScreen.addKeyboardPresses(WorldScreen.kt:277)
	at com.unciv.ui.worldscreen.WorldScreen.<init>(WorldScreen.kt:186)
	at com.unciv.UncivGame.loadGame(UncivGame.kt:154)
	at com.unciv.ui.newgamescreen.NewGameScreen$newGameThread$3.invoke(NewGameScreen.kt:313)
	at com.unciv.ui.newgamescreen.NewGameScreen$newGameThread$3.invoke(NewGameScreen.kt:312)
	at com.unciv.ui.utils.ExtensionFunctionsKt$wrapCrashHandling$1.invoke(ExtensionFunctions.kt:333)
	at com.unciv.ui.utils.ExtensionFunctionsKt$wrapCrashHandlingUnit$1.invoke(ExtensionFunctions.kt:360)
	at com.unciv.ui.utils.ExtensionFunctionsKt$wrapCrashHandlingUnit$1.invoke(ExtensionFunctions.kt:360)
	at com.unciv.ui.crashhandling.CrashHandlingThreadKt.postCrashHandlingRunnable$lambda-0(CrashHandlingThread.kt:26)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:159)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:63)

```

Yep, it crashes for me as well when using the functions with comments

**Comment by JackRainy** [comment]
Well... I had used the tool in the Android Studio: `File -> Invalidate caches...` and it has helped.
Thank you and sorry for a "noise", I will close the PR then.

**Comment by SomeTroglodyte** [comment]
No, **sorry** for not mass-alarming all of you earlier, I was on the verge of doing so about 20 minutes after the merge, but then... Maybe I didn't dare to spam?
