### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [yairm210/Unciv#5036]
https://gitlab.com/linsui/fdroiddata/-/jobs/1547670254#L2329

```
Preparing "Install Android SDK Build-Tools 30.0.2 (revision: 30.0.2)".
FAILURE: Build failed with an exception.
* What went wrong:
'void org.apache.commons.compress.archivers.zip.ZipFile.<init>(java.nio.channels.SeekableByteChannel)'
```

Could you please take a look? We got the same error when building https://github.com/00-Evan/shattered-pixel-dungeon so it may be some bug related to libgdx. Thanks!

**Comment by yairm210** [comment]
It looks to me like a problem using apache commons to pack a jar file, not libgdx related

We recently upgraded to gradle 7, and gradle 7 requires java 11 - maybe that's the problem? What java version runs on these runners?

**Comment by yairm210** [comment]
Ayup, it's java 8 openjdk :(
That's probably why it doesn't recognize the new apache commons library for jar packing
I'll check the shattered to see if they upgraded to gradle 7 as well

**Comment by yairm210** [comment]
https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/gradle/wrapper/gradle-wrapper.properties

Indeed
Changed 22 days ago
I did so sure to Android studio recommending the change in the recent version, which was this month

**Comment by linsui** [comment]
We are using java 11. Without java 11 we can't build the apk with the new gradle. https://gitlab.com/linsui/fdroiddata/-/jobs/1547670254#L2095

**Comment by linsui** [comment]
We have build lots of apks with gradle 7.1.1. Not sure what the difference is.

**Comment by linsui** [comment]
A libgdx app build fine with gradle 7.1.1. If it helps. https://github.com/mimoguz/tripeaks-gdx/tree/0.51

**Comment by yairm210** [comment]
https://stackoverflow.com/questions/52381075/apache-poi-java-lang-noclassdeffounderror-org-apache-commons-compress-archivers

Looks like it might be a build tools version problem?

**Comment by yairm210** [comment]
I see that https://github.com/mimoguz/tripeaks-gdx/blob/0.51/android/build.gradle specifies the build tools version, but at https://github.com/yairm210/Unciv/blob/master/android/build.gradle.kts (and for shattered ) we do not. The difference is 30.0.3 for tripeaks and 30.0.2 for us, which is so minor I doubt that's the right direction, but I really have no idea what this is about.

**Comment by linsui** [comment]
So you are using 30.0.3? I'll test it. Thanks!

**Comment by linsui** [comment]
30.0.3 doesn't work either. https://gitlab.com/linsui/fdroiddata/-/jobs/1549705272#L2266

**Comment by SomeTroglodyte** [comment]
I can repro the exact error message locally by:
- Use a Wincrap 10 box
- AND configure Android Studio to have SDK Tools 31 installed _but not_ 30.0.2

The Unciv build will pull 30.0.2 or try to and fail...

Note if this hits you can't build at all, long before any packaging.

**Comment by linsui** [comment]
https://gitlab.com/linsui/fdroiddata/-/jobs/1551380402#L2303

I add that to build.gradle but still failed.

**Comment by SomeTroglodyte** [comment]
What I meant is you use the tools _already on the box_ -or- provide a box that already has 30.0.2. In your output I only see it does have 27.0.3 - almost embarrassing. `Running with gitlab-runner 14.2.0-rc1` -> any others? Is it documented somewhere which tools they got preinstalled by default?

**Comment by linsui** [comment]
It's weird. Gradle should install it automatic. Currently we can't install it manully because we are using a sdkmanager broken on java 11...

**Comment by SomeTroglodyte** [comment]
> weird, automatic.

Exactly. It should but can't - at least that's my impression.

> broken on java

🤣 

So - we know one comparable candidate which builds: tripeaks, right? So, set our BuildTools explicitly to 30.0.3 _and_ push up gradle from 7.0.2 to 7.1.1 including wrapper perhaps... Better try locally first.

**Comment by linsui** [comment]
30.0.3+7.1.1 also failed. https://gitlab.com/linsui/fdroiddata/-/jobs/1551798182

**Comment by SomeTroglodyte** [comment]
I'm out of ideas. I can't get *anything* to work under gradle 7.1.1 locally, not even an AS sync. Back to status quo, there's that stack trace [(right where _your_ builds say you need an option to see it)](https://gitlab.com/linsui/fdroiddata/-/jobs/1551798182#L2310) - and it basically says: code not in our control (gradle) decides it needs to download that specific sdk build tools version, then calls google code for that (also outside our control), which then fails when it tries to call a method that doesn't exist on some zip api. Something is rotten to the core, and it's not ours.

So the only option I can think of remains - make sure it _doesn't_ need to download any sdk build tools.

<details><summary>monster stacktrace</summary>

```
***@***:~/Work/Unciv$ ./gradlew android:assemble --stacktrace
Checking the license for package Android SDK Build-Tools 30.0.2 in /home/bob/Android/Sdk/licenses
License for package Android SDK Build-Tools 30.0.2 accepted.
Preparing "Install Android SDK Build-Tools 30.0.2 (revision: 30.0.2)".

FAILURE: Build failed with an exception.

* What went wrong:
'void org.apache.commons.compress.archivers.zip.ZipFile.<init>(java.nio.channels.SeekableByteChannel)'

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.NoSuchMethodError: 'void org.apache.commons.compress.archivers.zip.ZipFile.<init>(java.nio.channels.SeekableByteChannel)'
        at com.android.repository.util.InstallerUtil.unzip(InstallerUtil.java:99)
        at com.android.repository.impl.installer.BasicInstaller.doPrepare(BasicInstaller.java:90)
        at com.android.repository.impl.installer.AbstractPackageOperation.prepare(AbstractPackageOperation.java:335)
        at com.android.builder.sdk.DefaultSdkLoader.installRemotePackages(DefaultSdkLoader.java:365)
        at com.android.builder.sdk.DefaultSdkLoader.installBuildTools(DefaultSdkLoader.java:318)
        at com.android.builder.sdk.DefaultSdkLoader.getTargetInfo(DefaultSdkLoader.java:155)
        at com.android.build.gradle.internal.SdkHandler.initTarget(SdkHandler.java:127)
        at com.android.build.gradle.internal.SdkFullLoadingStrategy.init(SdkFullLoadingStrategy.kt:49)
        at com.android.build.gradle.internal.SdkFullLoadingStrategy.getTargetBootClasspath(SdkFullLoadingStrategy.kt:70)
        at com.android.build.gradle.internal.SdkLoadingStrategy.getTargetBootClasspath(SdkLoadingStrategy.kt:35)
        at com.android.build.gradle.internal.SdkComponentsBuildService$VersionedSdkLoader$targetBootClasspathProvider$1.call(SdkComponents.kt:171)
        at com.android.build.gradle.internal.SdkComponentsBuildService$VersionedSdkLoader$targetBootClasspathProvider$1.call(SdkComponents.kt:170)
        at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:66)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:103)
        at org.gradle.api.internal.provider.FlatMapProvider.calculateOwnValue(FlatMapProvider.java:50)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:103)
        at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:64)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:84)
        at com.android.build.gradle.internal.scope.GlobalScope.lambda$getBootClasspath$6(GlobalScope.java:274)
        at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:66)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:84)
        at org.gradle.api.internal.provider.ProviderResolutionStrategy$2.resolve(ProviderResolutionStrategy.java:33)
        at org.gradle.api.internal.file.collections.ProviderBackedFileCollection.visitDependencies(ProviderBackedFileCollection.java:56)
        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext$TaskGraphImpl.getNodeValues(CachingTaskDependencyResolveContext.java:114)
        at org.gradle.internal.graph.CachingDirectedGraphWalker$GraphWithEmptyEdges.getNodeValues(CachingDirectedGraphWalker.java:213)
        at org.gradle.internal.graph.CachingDirectedGraphWalker.doSearch(CachingDirectedGraphWalker.java:121)
        at org.gradle.internal.graph.CachingDirectedGraphWalker.findValues(CachingDirectedGraphWalker.java:73)
        at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:69)
        at org.gradle.execution.plan.TaskDependencyResolver.resolveDependenciesFor(TaskDependencyResolver.java:46)
        at org.gradle.execution.plan.LocalTaskNode.getDependencies(LocalTaskNode.java:163)
        at org.gradle.execution.plan.LocalTaskNode.resolveDependencies(LocalTaskNode.java:131)
        at org.gradle.execution.plan.DefaultExecutionPlan.doAddNodes(DefaultExecutionPlan.java:186)
        at org.gradle.execution.plan.DefaultExecutionPlan.addEntryTasks(DefaultExecutionPlan.java:150)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.addEntryTasks(DefaultTaskExecutionGraph.java:157)
        at org.gradle.execution.TaskNameResolvingBuildConfigurationAction.configure(TaskNameResolvingBuildConfigurationAction.java:49)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:55)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:26)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:63)
        at org.gradle.execution.DefaultTasksBuildExecutionAction.configure(DefaultTasksBuildExecutionAction.java:45)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:55)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:26)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:63)
        at org.gradle.execution.ExcludedTaskFilteringBuildConfigurationAction.configure(ExcludedTaskFilteringBuildConfigurationAction.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:55)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.lambda$select$0(DefaultBuildConfigurationActionExecuter.java:42)
        at org.gradle.internal.Factories$1.create(Factories.java:31)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry.withMutableStateOfAllProjects(DefaultProjectStateRegistry.java:141)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry.withMutableStateOfAllProjects(DefaultProjectStateRegistry.java:128)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.select(DefaultBuildConfigurationActionExecuter.java:40)
        at org.gradle.initialization.DefaultTaskExecutionPreparer.prepareForTaskExecution(DefaultTaskExecutionPreparer.java:38)
        at org.gradle.initialization.BuildOperationFiringTaskExecutionPreparer$CalculateTaskGraph.populateTaskGraph(BuildOperationFiringTaskExecutionPreparer.java:117)
        at org.gradle.initialization.BuildOperationFiringTaskExecutionPreparer$CalculateTaskGraph.run(BuildOperationFiringTaskExecutionPreparer.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:71)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:71)
        at org.gradle.initialization.BuildOperationFiringTaskExecutionPreparer.prepareForTaskExecution(BuildOperationFiringTaskExecutionPreparer.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.prepareTaskExecution(DefaultGradleLauncher.java:233)
        at org.gradle.initialization.DefaultGradleLauncher.doClassicBuildStages(DefaultGradleLauncher.java:168)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
        at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:125)
        at org.gradle.internal.invocation.GradleBuildController$1.create(GradleBuildController.java:71)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:213)
        at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:67)
        at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:56)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:31)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:66)
        at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
        at org.gradle.tooling.internal.provider.FileSystemWatchingBuildActionRunner.run(FileSystemWatchingBuildActionRunner.java:90)
        at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:41)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:49)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:44)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:44)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.lambda$execute$0(InProcessBuildActionExecuter.java:59)
        at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:58)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.lambda$execute$0(BuildTreeScopeLifecycleBuildActionExecuter.java:34)
        at org.gradle.internal.buildtree.BuildTreeState.run(BuildTreeState.java:53)
        at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.execute(BuildTreeScopeLifecycleBuildActionExecuter.java:33)
        at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.execute(BuildTreeScopeLifecycleBuildActionExecuter.java:28)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:104)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:55)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:64)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:37)
        at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.lambda$execute$0(SessionScopeLifecycleBuildActionExecuter.java:54)
        at org.gradle.internal.session.BuildSessionState.run(BuildSessionState.java:67)
        at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.execute(SessionScopeLifecycleBuildActionExecuter.java:50)
        at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.execute(SessionScopeLifecycleBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:58)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:42)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:47)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:31)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:65)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:84)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)


* Get more help at https://help.gradle.org

BUILD FAILED in 2s
```
</details>

**Comment by linsui** [comment]
Some more tests:
Tripeak uses AGP 4.2.2. But it also works with AGP 7.0.0. https://gitlab.com/linsui/fdroiddata/-/jobs/1561611022
A difference is that Tripeak installs sdk when clean. Is that related to org.gradle.configureondemand=false? I tried to add that to unciv's gradle.properties but failed. https://gitlab.com/linsui/fdroiddata/-/jobs/1561274098
I saw the same error in https://github.com/Anuken/Mindustry. Yes, it's another libgdx app.

**Comment by SomeTroglodyte** [comment]
AGP - the studio plugin? I would have thought its effects limited to UI and zero effect on command line builds. But then I'm no expert that would have been a pure prejudice...

And of course I know the guy who's done our jar packer also does a game :wink:

Still haven't got any 'eureka' moment.

**Comment by linsui** [comment]
It's AGP 7 which requires java 11 and build-tools 30.0.2.

**Comment by linsui** [comment]
I find that I can use sdkmanager with java 8 by setting JAVA_HOME. So the latest version is built now. But this is just a work around.

**Comment by SomeTroglodyte** [comment]
Wow. Thanks for your persistent efforts!

Q: How to move on?
- Did we find out why exactly the on-demand download of tools fails? Is it a gradle bug needs reporting? I mean, pre-G7 that worked, or did we always have enormous luck to get configs expecting tools that were already there?
- Specifying a specific tools version never worked because we didn't hit the one version the VM already has available and needs no downloads, do I remember this right? So it may be a good thing to know which pre-loaded sdk tool versions future f-droid build VM's will come with?

**Comment by linsui** [comment]
> Did we find out why exactly the on-demand download of tools fails? Is it a gradle bug needs reporting? I mean, pre-G7 that worked, or did we always have enormous luck to get configs expecting tools that were already there?

I thought the SDK is downloaded by AGP so it's an AGP bug. I'm not an Android developer so I'm not sure.

> Specifying a specific tools version never worked because we didn't hit the one version the VM already has available and needs no downloads, do I remember this right? So it may be a good thing to know which pre-loaded sdk tool versions future f-droid build VM's will come with?

We currently use built-tool 27. We may use 31 by default when we upgrading to debian bulleye. I'm not sure.

**Comment by yairm210** [comment]
Since 3.16.12, versions have been successfully uploaded as usual.
That's 2 versions already, so it seems consistency is back
The question of "what changed" remains, for me at least, unresolved

**Comment by yairm210** [comment]
One thing that changed was reverting compileSdk and targetSdk to 30, from 31. But you say that Mindustry had the same error, and it's on 30 as well, so it can't be just that

**Comment by yairm210** [comment]
Another thing that changed was upgrading to Kotlin 1.5.30 from 1.4.30, this changing JDK compatibility from 1.7 to 1.8, but again that's not a good indicator. Mindustry is java only, Shattered is also 1.8-compliant. I can't see any difference that was made that would set Unciv apart from either of them.

**Comment by yairm210** [comment]
Since the build itself is now successful, I'm closing this issue, but I still feel that this is caused by don't combination of unknown factirs, solve it which may or may not be the ones I've mentioned.

@linsui thank you for all your enduring hard work on this exasperating problem!
