### ISSUE TITLE
Instant crash after update to 4.12.12 - SOLVED with 4.12.12-patch1

### ISSUE THREAD

**Issue by Mape6** [yairm210/Unciv#11987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.12

### Describe the bug

**Platform:** Android
**Version:** 4.12.12 (Build 1.025)
**Rulesets:** [Civ V - Vanilla, Civ V - Gods & Kings]
**Last Screen:** `com.unciv.GameStartScreen`

--------------------------------

Device Model: Pixel 7a
API Level: 34
System Memory: 7477 MB
    Available (used by Kernel): 2103 MB
    System Low Memory state: false
    Java heap limit: 512 MB
    Java heap free: 21 MB

--------------------------------

**Message:**
```
java.lang.NoSuchMethodError: No static method ofInstant(Lj$/time/Instant;Lj$/time/ZoneId;)Lj$/time/LocalDate; in class Lj$/time/LocalDate; or its super classes (declaration of 'j$.time.LocalDate' appears in /data/app/~~6FRD8VtNMo5MAxR-ycFVeQ==/com.unciv.app-DMA2QxLD8SOgQ0C1w21CZQ==/base.apk!classes3.dex)
	at com.unciv.logic.HolidayDates$Holidays$Qingming.getByYear(HolidayDates.kt:64)
	at com.unciv.logic.HolidayDates.getHolidayByDate(HolidayDates.kt:159)
	at com.unciv.logic.HolidayDates.getHolidayByDate$default(HolidayDates.kt:155)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen.<init>(MainMenuScreen.kt:123)
	at com.unciv.UncivGame$create$3$1.invokeSuspend(UncivGame.kt:172)
	at com.unciv.UncivGame$create$3$1.invoke(Unknown Source:8)
	at com.unciv.UncivGame$create$3$1.invoke(Unknown Source:4)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:89)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:190)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:190)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:190)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher.$r8$lambda$1exBTjTJ644h9iUU94EW5nQQXpM(Unknown Source:0)
	at com.unciv.utils.Dispatchers$CrashHandlingDispatcher$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:498)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1573)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

```

### Steps to Reproduce

1. Try to open the app

### Operating System

Android

**Comment by yairm210** [comment]
I'll fix this in a patch
@SomeTroglodyte looks like Android doesn't have the java time primitives for this :/

**Comment by Mape6** [comment]
Issue solved with patch1 release.
