### ISSUE TITLE
UncivServer doesn't work on Windows, The Client sends Empty Body at `PUT /files/:fileName`

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#6547]
**Platform**
Windows (Android Works)

**Version**
4.0.6

**Describe the bug**
Create new Game and Next Turn doesn't work on Online Multiplayer.
When I check the Error Logs at **UncivServer.xyz** I found out that the Client was sending Empty Body at `PUT /files/:fileName`.
@ravignir tested this on [UncivServer](https://yairm210.github.io/Unciv/Other/Hosting-a-Multiplayer-server/) and found that it doen't either.

**Steps to Reproduce**
Connect to https://uncivserver.xyz or try to host your own Multiplyer Server.
Try to Create a new Game or do Next Turn on Windows.
Try to do the same on Andorid.

**Expected Behaviour**
Both Works

**Actual Behavior**
Windows doesn't

**Comment by Mape6** [comment]
I tested this with my Unciv_server written in Python and it is working fine with Unciv 4.0.6-patch1 on Windows.

With the Unciv shipped HTTP server the PUT method is not working. GET is working fine but PUT generates the following error:
```13:29:40.769 [eventLoopGroupProxy-4-6] ERROR ktor.application - Unhandled: PUT - /files/a3a79fc7-8c72-44c6-bcdf-34ad5fb5579e
java.lang.NoSuchMethodError: java.io.InputStream.readAllBytes()[B
        at com.unciv.app.desktop.UncivServerRunner$serverRun$1$1$2$1.invokeSuspend(UncivServer.kt:52)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)```

**Comment by touhidurrr** [comment]
> I tested this with my Unciv_server written in Python and it is working fine with Unciv 4.0.6-patch1 on Windows.
> 
> With the Unciv shipped HTTP server the PUT method is not working. GET is working fine but PUT generates the following error:
> 
> ```
> java.lang.NoSuchMethodError: java.io.InputStream.readAllBytes()[B
>         at com.unciv.app.desktop.UncivServerRunner$serverRun$1$1$2$1.invokeSuspend(UncivServer.kt:52)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)```
> ```

If it is working then it is a problem itself. Why would the server accept empty bodies to rewrite game data?

**Comment by Mape6** [comment]
> Are you not getting empty bodies?

Nope, my files always have data in it. I created three new games and played in about 20 turns every game.

**Comment by touhidurrr** [comment]
> > Are you not getting empty bodies?
> 
> Nope, my files always have data in it. I created three new games and played about 20 turns in every game.

1. Are you testing on Windows?
2. There are two type of game file. Are you sure non of them is empty at any point?

**Comment by touhidurrr** [comment]
> > > Are you not getting empty bodies?
> > 
> > 
> > Nope, my files always have data in it. I created three new games and played about 20 turns in every game.
> 
> 1. Are you testing on Windows?
> 2. There are two type of game file. Are you sure non of them is empty at any point?

I am still seeing the issue.

**Comment by yairm210** [comment]
What was the problem?

**Comment by touhidurrr** [comment]
> What was the problem?

The Text Body parser that I was using to parse request Bodies at UncivServer.xyz was Mysteriously failing only for Windows. I wrote a new custom one and it got fixed by itself.

Possible Reasons:
Windows not sending any `Content-Type` header (not sure, cause in my personal tests I never use those headers after all)

About the default UncivServer, I don’t know why it is not working.
